name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    # Only run if the push is to master AND has a tag
    if: github.ref_type == 'tag' && github.event.base_ref == 'refs/heads/master'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PERSONAL_ACCESS_TOKEN }}

    - name: Extract tag name
      id: extract_tag
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile
        push: true
        tags: |
          ${{ vars.DOCKER_REPOSITORY }}:${{ steps.extract_tag.outputs.tag }}
          ${{ vars.DOCKER_REPOSITORY }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
